dist: xenial
language: python
python:
- "3.8"
- "3.7"
- "3.6"
install:
- pip install -U pandas click tqdm
- pip install -U sphinx ipython travis-sphinx
- pip install -U numpydoc sphinxcontrib-fulltoc guzzle_sphinx_theme
- pip install git+https://github.com/leokoppel/sphinxcontrib-versioning.git
- pip install -U pytest coverage pytest-cov codecov black flake8
- wget -c https://download.asperasoft.com/download/sw/connect/3.8.1/ibm-aspera-connect-3.8.1.161274-linux-g2.12-64.tar.gz && tar -zxvf ibm-aspera-connect-3.8.1.161274-linux-g2.12-64.tar.gz && bash ibm-aspera-connect-3.8.1.161274-linux-g2.12-64.sh
- make install
script:
- pysradb
  #- flake8
- black --check .
  #- pytest -s -v tests
  #- make test
- make coverage
- codecov
- travis-sphinx build --source=$TRAVIS_BUILD_DIR/docs
  #- sphinx-versioning build $TRAVIS_BUILD_DIR/docs/ $TRAVIS_BUILD_DIR/docs/_build/html/
after_success:
- travis-sphinx deploy
deploy:
  provider: pypi
  distributions: sdist bdist bdist_wheel
  user: saketkc
  password:
    secure: CHb2u5l7Psxa5AeXdWR3c8FDUG7ESQYUla/B3ARwi8cwCrcwrocM7uHuxlK6CchY3HT5qL4lNDDU2ElDFZIl8m9+Hg8yH193/2VdwbTT9jd8yCKZjWQWL1vbd/w6gijWaVR+n1ZHe6LKSahNhhl+8FEU65WjdUx/socYdUjwXNECrNobskubU0NghUDK9+8ND6iV195OJGk32jjxlCF00MhsX9mw+ZS0MDR34hzkMyknzSkzGrbFf5JYkQOJbTNAP6ajCp3C5Kgm1XbkjCyV0rhBA7d0snfMF+3mTtH4ZNmyUSZe3OONiZFdmJEncVDKxsaR0CdvEy7qoA4FgqN5q1hTXQYd5ZCJLPujpn1iMkxsqdjI3e6aH0knrv+dgPYHLQxANAmzlkfP0CWiG/9KzpbF4eeDk6rWvf5RgP00wOUi1H4bpDx5aA8nAXPNWoYl31KWQH7UbJ9zrdgsAD8jgBc3XN6sozK4z5AIvXdUEm/hqba4DB3sJ2lyFRfeky6vYlMfxwAVL+YMlQnyE1P3kbaVSy01rQroTzPp3fnArUiIsqlGcIemV9Eu6UNpTInODzr9uFmcEL3GGQhRQXgYiVsJSzZjBnkoFKldj0LMdn8t5HZbl4vEDLGdYgMgk3281C9MMp4K+eSL650eL3ymrCRc3uz3+2Vn4EaZk2b6Hh0=
  on:
    branch: master
    tags: true
    repo: pysradb
    skip_existing: true
